language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpspec.yml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpspec.yml.hhvm.7 phpspec.yml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then rm phpspec.yml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then mv phpspec.yml.hhvm.7 phpspec.yml; fi

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpspec run
